/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Plain$Params {
  subjectId: number;
}

export function apiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<any>>> {
  const rb = new RequestBuilder(rootUrl, apiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('subjectId', params.subjectId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<any>>;
    })
  );
}

apiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Plain.PATH = '/api/StudentSubjects/GetStudentSubjectsBySubjectId/{subjectId}';
