/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DtoStudentSubject } from '../../models/dto-student-subject';
import { StudentSubject } from '../../models/student-subject';

export interface ApiStudentSubjectsPost$Json$Params {
      body?: DtoStudentSubject
}

export function apiStudentSubjectsPost$Json(http: HttpClient, rootUrl: string, params?: ApiStudentSubjectsPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentSubject>> {
  const rb = new RequestBuilder(rootUrl, apiStudentSubjectsPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StudentSubject>;
    })
  );
}

apiStudentSubjectsPost$Json.PATH = '/api/StudentSubjects';
