/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CreditProgram } from './models/credit-program';
export type { DateOnly } from './models/date-only';
export { DayOfWeek } from './models/day-of-week';
export type { DtoStudent } from './models/dto-student';
export type { DtoStudentSubject } from './models/dto-student-subject';
export type { Student } from './models/student';
export type { StudentSubject } from './models/student-subject';
export type { Subject } from './models/subject';
export type { Teacher } from './models/teacher';
export type { TeacherSubject } from './models/teacher-subject';
export type { WeatherForecast } from './models/weather-forecast';
