/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { CreditProgramsService } from './services/credit-programs.service';
export { StudentSubjectsService } from './services/student-subjects.service';
export { StudentsService } from './services/students.service';
export { SubjectsService } from './services/subjects.service';
export { WeatherForecastService } from './services/weather-forecast.service';
