/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Student } from '../models/student';
import { Subject } from '../models/subject';
export interface CreditProgram {
  description?: string | null;
  idCreditProgram?: number;
  name?: string | null;
  students?: Array<Student> | null;
  subjects?: Array<Subject> | null;
}
