/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DtoStudentSubject {
  idStudent: number;
  idStudentSubject?: number;
  subjectId: number;
}
