/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Student } from '../models/student';
import { Subject } from '../models/subject';
export interface StudentSubject {
  idStudent?: number | null;
  idStudentNavigation?: Student;
  idStudentSubject?: number;
  subject?: Subject;
  subjectId?: number | null;
}
