/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreditProgram } from '../models/credit-program';
import { StudentSubject } from '../models/student-subject';
export interface Student {
  idCreditProgram?: number | null;
  idCreditProgramNavigation?: CreditProgram;
  idStudent?: number;
  name?: string | null;
  numberDocument?: string | null;
  studentSubjects?: Array<StudentSubject> | null;
}
