/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreditProgram } from '../models/credit-program';
import { StudentSubject } from '../models/student-subject';
import { TeacherSubject } from '../models/teacher-subject';
export interface Subject {
  credits?: number;
  idCreditProgram?: number | null;
  idCreditProgramNavigation?: CreditProgram;
  idSubject?: number;
  name?: string | null;
  studentSubjects?: Array<StudentSubject> | null;
  teacherSubjects?: Array<TeacherSubject> | null;
}
