/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TeacherSubject } from '../models/teacher-subject';
export interface Teacher {
  idTeacher?: number;
  name?: string | null;
  teacherSubjects?: Array<TeacherSubject> | null;
}
