/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Subject } from '../models/subject';
import { Teacher } from '../models/teacher';
export interface TeacherSubject {
  id?: number;
  subject?: Subject;
  subjectId?: number | null;
  teacher?: Teacher;
  teacherId?: number | null;
}
