/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiCreditProgramsGet$Json } from '../fn/credit-programs/api-credit-programs-get-json';
import { ApiCreditProgramsGet$Json$Params } from '../fn/credit-programs/api-credit-programs-get-json';
import { apiCreditProgramsGet$Plain } from '../fn/credit-programs/api-credit-programs-get-plain';
import { ApiCreditProgramsGet$Plain$Params } from '../fn/credit-programs/api-credit-programs-get-plain';

@Injectable({ providedIn: 'root' })
export class CreditProgramsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiCreditProgramsGet()` */
  static readonly ApiCreditProgramsGetPath = '/api/CreditPrograms';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCreditProgramsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCreditProgramsGet$Plain$Response(params?: ApiCreditProgramsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<any>>> {
    return apiCreditProgramsGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCreditProgramsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCreditProgramsGet$Plain(params?: ApiCreditProgramsGet$Plain$Params, context?: HttpContext): Observable<Array<any>> {
    return this.apiCreditProgramsGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<any>>): Array<any> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCreditProgramsGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCreditProgramsGet$Json$Response(params?: ApiCreditProgramsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<any>>> {
    return apiCreditProgramsGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCreditProgramsGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCreditProgramsGet$Json(params?: ApiCreditProgramsGet$Json$Params, context?: HttpContext): Observable<Array<any>> {
    return this.apiCreditProgramsGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<any>>): Array<any> => r.body)
    );
  }

}
