/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiStudentsGet$Json } from '../fn/students/api-students-get-json';
import { ApiStudentsGet$Json$Params } from '../fn/students/api-students-get-json';
import { apiStudentsGet$Plain } from '../fn/students/api-students-get-plain';
import { ApiStudentsGet$Plain$Params } from '../fn/students/api-students-get-plain';
import { apiStudentsIdDelete } from '../fn/students/api-students-id-delete';
import { ApiStudentsIdDelete$Params } from '../fn/students/api-students-id-delete';
import { apiStudentsIdGet } from '../fn/students/api-students-id-get';
import { ApiStudentsIdGet$Params } from '../fn/students/api-students-id-get';
import { apiStudentsIdPut } from '../fn/students/api-students-id-put';
import { ApiStudentsIdPut$Params } from '../fn/students/api-students-id-put';
import { apiStudentsPost$Json } from '../fn/students/api-students-post-json';
import { ApiStudentsPost$Json$Params } from '../fn/students/api-students-post-json';
import { apiStudentsPost$Plain } from '../fn/students/api-students-post-plain';
import { ApiStudentsPost$Plain$Params } from '../fn/students/api-students-post-plain';
import { Student } from '../models/student';

@Injectable({ providedIn: 'root' })
export class StudentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiStudentsGet()` */
  static readonly ApiStudentsGetPath = '/api/Students';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudentsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentsGet$Plain$Response(params?: ApiStudentsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<any>>> {
    return apiStudentsGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudentsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentsGet$Plain(params?: ApiStudentsGet$Plain$Params, context?: HttpContext): Observable<Array<any>> {
    return this.apiStudentsGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<any>>): Array<any> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudentsGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentsGet$Json$Response(params?: ApiStudentsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<any>>> {
    return apiStudentsGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudentsGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentsGet$Json(params?: ApiStudentsGet$Json$Params, context?: HttpContext): Observable<Array<any>> {
    return this.apiStudentsGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<any>>): Array<any> => r.body)
    );
  }

  /** Path part for operation `apiStudentsPost()` */
  static readonly ApiStudentsPostPath = '/api/Students';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudentsPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiStudentsPost$Plain$Response(params?: ApiStudentsPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Student>> {
    return apiStudentsPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudentsPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiStudentsPost$Plain(params?: ApiStudentsPost$Plain$Params, context?: HttpContext): Observable<Student> {
    return this.apiStudentsPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Student>): Student => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudentsPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiStudentsPost$Json$Response(params?: ApiStudentsPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Student>> {
    return apiStudentsPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudentsPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiStudentsPost$Json(params?: ApiStudentsPost$Json$Params, context?: HttpContext): Observable<Student> {
    return this.apiStudentsPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Student>): Student => r.body)
    );
  }

  /** Path part for operation `apiStudentsIdGet()` */
  static readonly ApiStudentsIdGetPath = '/api/Students/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudentsIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentsIdGet$Response(params: ApiStudentsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiStudentsIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudentsIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentsIdGet(params: ApiStudentsIdGet$Params, context?: HttpContext): Observable<void> {
    return this.apiStudentsIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiStudentsIdPut()` */
  static readonly ApiStudentsIdPutPath = '/api/Students/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudentsIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiStudentsIdPut$Response(params: ApiStudentsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiStudentsIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudentsIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiStudentsIdPut(params: ApiStudentsIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiStudentsIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiStudentsIdDelete()` */
  static readonly ApiStudentsIdDeletePath = '/api/Students/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudentsIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentsIdDelete$Response(params: ApiStudentsIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiStudentsIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudentsIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentsIdDelete(params: ApiStudentsIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiStudentsIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
