/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiStudentSubjectsGet$Json } from '../fn/student-subjects/api-student-subjects-get-json';
import { ApiStudentSubjectsGet$Json$Params } from '../fn/student-subjects/api-student-subjects-get-json';
import { apiStudentSubjectsGet$Plain } from '../fn/student-subjects/api-student-subjects-get-plain';
import { ApiStudentSubjectsGet$Plain$Params } from '../fn/student-subjects/api-student-subjects-get-plain';
import { apiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Json } from '../fn/student-subjects/api-student-subjects-get-student-subjects-by-subject-id-subject-id-get-json';
import { ApiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Json$Params } from '../fn/student-subjects/api-student-subjects-get-student-subjects-by-subject-id-subject-id-get-json';
import { apiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Plain } from '../fn/student-subjects/api-student-subjects-get-student-subjects-by-subject-id-subject-id-get-plain';
import { ApiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Plain$Params } from '../fn/student-subjects/api-student-subjects-get-student-subjects-by-subject-id-subject-id-get-plain';
import { apiStudentSubjectsIdDelete } from '../fn/student-subjects/api-student-subjects-id-delete';
import { ApiStudentSubjectsIdDelete$Params } from '../fn/student-subjects/api-student-subjects-id-delete';
import { apiStudentSubjectsIdGet$Json } from '../fn/student-subjects/api-student-subjects-id-get-json';
import { ApiStudentSubjectsIdGet$Json$Params } from '../fn/student-subjects/api-student-subjects-id-get-json';
import { apiStudentSubjectsIdGet$Plain } from '../fn/student-subjects/api-student-subjects-id-get-plain';
import { ApiStudentSubjectsIdGet$Plain$Params } from '../fn/student-subjects/api-student-subjects-id-get-plain';
import { apiStudentSubjectsPost$Json } from '../fn/student-subjects/api-student-subjects-post-json';
import { ApiStudentSubjectsPost$Json$Params } from '../fn/student-subjects/api-student-subjects-post-json';
import { apiStudentSubjectsPost$Plain } from '../fn/student-subjects/api-student-subjects-post-plain';
import { ApiStudentSubjectsPost$Plain$Params } from '../fn/student-subjects/api-student-subjects-post-plain';
import { StudentSubject } from '../models/student-subject';

@Injectable({ providedIn: 'root' })
export class StudentSubjectsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiStudentSubjectsGet()` */
  static readonly ApiStudentSubjectsGetPath = '/api/StudentSubjects';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudentSubjectsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentSubjectsGet$Plain$Response(params?: ApiStudentSubjectsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<any>>> {
    return apiStudentSubjectsGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudentSubjectsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentSubjectsGet$Plain(params?: ApiStudentSubjectsGet$Plain$Params, context?: HttpContext): Observable<Array<any>> {
    return this.apiStudentSubjectsGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<any>>): Array<any> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudentSubjectsGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentSubjectsGet$Json$Response(params?: ApiStudentSubjectsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<any>>> {
    return apiStudentSubjectsGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudentSubjectsGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentSubjectsGet$Json(params?: ApiStudentSubjectsGet$Json$Params, context?: HttpContext): Observable<Array<any>> {
    return this.apiStudentSubjectsGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<any>>): Array<any> => r.body)
    );
  }

  /** Path part for operation `apiStudentSubjectsPost()` */
  static readonly ApiStudentSubjectsPostPath = '/api/StudentSubjects';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudentSubjectsPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiStudentSubjectsPost$Plain$Response(params?: ApiStudentSubjectsPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentSubject>> {
    return apiStudentSubjectsPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudentSubjectsPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiStudentSubjectsPost$Plain(params?: ApiStudentSubjectsPost$Plain$Params, context?: HttpContext): Observable<StudentSubject> {
    return this.apiStudentSubjectsPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudentSubject>): StudentSubject => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudentSubjectsPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiStudentSubjectsPost$Json$Response(params?: ApiStudentSubjectsPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentSubject>> {
    return apiStudentSubjectsPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudentSubjectsPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiStudentSubjectsPost$Json(params?: ApiStudentSubjectsPost$Json$Params, context?: HttpContext): Observable<StudentSubject> {
    return this.apiStudentSubjectsPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudentSubject>): StudentSubject => r.body)
    );
  }

  /** Path part for operation `apiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet()` */
  static readonly ApiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGetPath = '/api/StudentSubjects/GetStudentSubjectsBySubjectId/{subjectId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Plain$Response(params: ApiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<any>>> {
    return apiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Plain(params: ApiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Plain$Params, context?: HttpContext): Observable<Array<any>> {
    return this.apiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<any>>): Array<any> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Json$Response(params: ApiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<any>>> {
    return apiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Json(params: ApiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Json$Params, context?: HttpContext): Observable<Array<any>> {
    return this.apiStudentSubjectsGetStudentSubjectsBySubjectIdSubjectIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<any>>): Array<any> => r.body)
    );
  }

  /** Path part for operation `apiStudentSubjectsIdGet()` */
  static readonly ApiStudentSubjectsIdGetPath = '/api/StudentSubjects/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudentSubjectsIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentSubjectsIdGet$Plain$Response(params: ApiStudentSubjectsIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<any>>> {
    return apiStudentSubjectsIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudentSubjectsIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentSubjectsIdGet$Plain(params: ApiStudentSubjectsIdGet$Plain$Params, context?: HttpContext): Observable<Array<any>> {
    return this.apiStudentSubjectsIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<any>>): Array<any> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudentSubjectsIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentSubjectsIdGet$Json$Response(params: ApiStudentSubjectsIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<any>>> {
    return apiStudentSubjectsIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudentSubjectsIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentSubjectsIdGet$Json(params: ApiStudentSubjectsIdGet$Json$Params, context?: HttpContext): Observable<Array<any>> {
    return this.apiStudentSubjectsIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<any>>): Array<any> => r.body)
    );
  }

  /** Path part for operation `apiStudentSubjectsIdDelete()` */
  static readonly ApiStudentSubjectsIdDeletePath = '/api/StudentSubjects/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiStudentSubjectsIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentSubjectsIdDelete$Response(params: ApiStudentSubjectsIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiStudentSubjectsIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiStudentSubjectsIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiStudentSubjectsIdDelete(params: ApiStudentSubjectsIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiStudentSubjectsIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
