/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiSubjectsIdGet$Json } from '../fn/subjects/api-subjects-id-get-json';
import { ApiSubjectsIdGet$Json$Params } from '../fn/subjects/api-subjects-id-get-json';
import { apiSubjectsIdGet$Plain } from '../fn/subjects/api-subjects-id-get-plain';
import { ApiSubjectsIdGet$Plain$Params } from '../fn/subjects/api-subjects-id-get-plain';

@Injectable({ providedIn: 'root' })
export class SubjectsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiSubjectsIdGet()` */
  static readonly ApiSubjectsIdGetPath = '/api/Subjects/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSubjectsIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSubjectsIdGet$Plain$Response(params: ApiSubjectsIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<any>>> {
    return apiSubjectsIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSubjectsIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSubjectsIdGet$Plain(params: ApiSubjectsIdGet$Plain$Params, context?: HttpContext): Observable<Array<any>> {
    return this.apiSubjectsIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<any>>): Array<any> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSubjectsIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSubjectsIdGet$Json$Response(params: ApiSubjectsIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<any>>> {
    return apiSubjectsIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSubjectsIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSubjectsIdGet$Json(params: ApiSubjectsIdGet$Json$Params, context?: HttpContext): Observable<Array<any>> {
    return this.apiSubjectsIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<any>>): Array<any> => r.body)
    );
  }

}
